# Generated by Django 3.2.4 on 2021-06-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
