# Generated by Django 3.2.4 on 2021-06-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.price'),
        ),
    ]
