# Generated by Django 3.2.4 on 2021-06-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=17, null=True),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
