# Generated by Django 3.2.4 on 2021-06-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210619_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nesting_level',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
    ]
