# Generated by Django 3.2.4 on 2021-07-04 06:32

import A.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='detail',
            field=models.TextField(default='no details yet'),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.CharField(blank=True, default=A.utils.shamsi_date, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='more_detail',
            field=models.TextField(default='no details yet'),
        ),
    ]
