# Generated by Django 3.2.4 on 2021-07-17 09:55

import A.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210710_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': '8. Images'},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='size',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='description',
            field=models.CharField(blank=True, default='test', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, default=A.utils.shamsi_date, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.CharField(blank=True, default='test', max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
